### ISSUE TITLE
OpenMM plugin for clusters MB-pol/MB-nrg [WIP]

### ISSUE THREAD

**Issue by chemphys** [paesanilab/MBX#40]
Opening this issue to keep track of the OpenMM plugin implementation.

@dgasmith , I don't know which is the best practice for this, so any input and advice you can give to me regarding on how to structure it would be appreciated.

My idea is to create a new folder in (src?) with the openMM plugin. Do you think that is OK, or is better to create a folder in the home directory of the code called "clusters_ultimate" and another called "OpenMM_plugin"?

The idea I have in mind of this repo is that we will have a library that will contain the black box (input XYZ, output gradients and energy) that will be linked to different codes (for now only openMM, but maybe later we want to put it somewhere else). Which is the best way to structure this?

Thanks!

**Comment by dgasmith** [comment]
It could go either way. What do OpenMM plugins usually do?

-Daniel Smith

**Comment by chemphys** [comment]
It is usually a whole repo for the plugin itself.

**Comment by chemphys** [comment]
For now I am putting it in src. This way I can use the same CMake structure. If we think that we can reorganize that later, it won't be that bad to do.

I will keep you updated!

**Comment by chemphys** [comment]
@zonca , the tree of the plugin has to be that one? I mean, is it necessary to have the include and the src folder separately, with the include/openmm/internal ... etc stuff? Or can I have it as I want? Thanks!

**Comment by zonca** [comment]
it is better to keep the same structure, so if somebody else already familiar with OpenMM looks at the plugin it finds the usual plugin structure.

**Comment by chemphys** [comment]
Perfect. thanks! 
Next wednesday I would like to have another chat with you to make a basic example to work. Hopefully I will have a good understanding of the plugins by then, and we can have a high level conversation. 

Thank you!

**Comment by chemphys** [comment]
Hey @zonca ,

I think I have been able to put my classes and functions into the plugin. Now I need to do some stuff, but there are some questions you might be able to answer.

1. I have a System class, but I need to fill it with the coordinates and the monomer types when I initialize. This has to be done only once, since later I just need to update coordinates. Do I need to define the monomers in the XML? How can I loop over all the residues in the context? I have not been able to find this information.
2. Which is the function in the implementation that is called only once in the entire simulation? I think it was initialize(), but I would appreciate if you can confirm that.

Thanks!

**Comment by zonca** [comment]
1.  for now just assume that you always and only have `OHH` `OHH` so you can get it working, then later we can find a more general solution
2. yes, `initialize`

**Comment by chemphys** [comment]
@zonca , I finished the plugin. The [test](https://github.com/chemphys/clusters_ultimate/tree/mrr/openmm_plugin/plugins/openmm/platforms/reference/tests) that is testing the cpp version of the plugin works fine. The libraries are installed in the openmm directory, and they work fine.
The problem is in the python part. I added a silly test file for python [here](https://github.com/chemphys/clusters_ultimate/blob/mrr/openmm_plugin/plugins/openmm/tests/water3.py) that fails in [this line](https://github.com/chemphys/clusters_ultimate/blob/mrr/openmm_plugin/plugins/openmm/tests/water3.py#L19), complaining with:
```
Traceback (most recent call last):
  File "water3.py", line 19, in <module>
    system = forcefield.createSystem(pdb.topology)
  File "/home/mrierari/codes/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1128, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (HOH).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.
```
I do have defined the monomer in [the xml file](https://github.com/chemphys/clusters_ultimate/blob/mrr/openmm_plugin/plugins/openmm/python/mbnrg.xml), and if you look at the python test, I actually need to give the complete path because it is not finding it by default, I don't know why.

I would appreciate if you can have a look, assuming that the cpp part of the plugin works well (which it seems it does), and let me know if you see something wrong that my lack of knowledge is missing... Thanks!

**Comment by zonca** [comment]
I don't see your parser, a Python file that parses the xml, the equivalent of this: https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/mbpol.py

**Comment by chemphys** [comment]
So I do need that too... OK, I will write it. 
Thanks Andrea!

**Comment by chemphys** [comment]
I added it, but there might be something weird with the paths. It still doesn't find the XML. If I manually copy it to where it looks for it, it still does not recognize the HOH residue. I compared your [cmakelists](https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/CMakeLists.txt) file with [mine](https://github.com/chemphys/clusters_ultimate/blob/mrr/openmm_plugin/plugins/openmm/python/CMakeLists.txt) and everything seems consistent. It seems to install the libraries properly in the openmm folder, but it does not install mbnrg.py and mbnrg.xml.
Any idea?

By the way, I think I found a way to add the different monomers :) In the input parser you do something with the angles, and I see that there is a "particle class", which I can loop over and find all the monomers. Will requires a little bit of workthrough though.

**Comment by zonca** [comment]
You also need make PythonInstall

Il mar 6 mar 2018, 19:00 Marc Riera Riambau <notifications@github.com> ha
scritto:

**Comment by chemphys** [comment]
I did that.

**Comment by zonca** [comment]
Try directly python setup.py install from the python folder. That is a simple python package install, it should always work.

**Comment by chemphys** [comment]
It doesn't work either. Let's see if we can figure this out tomorrow together.

**Comment by chemphys** [comment]
So, seems like it is working. I will run some benchmarks over the weekend, and see how long does it take to get 100 MD steps and how does this scale with the number of threads. I will keep you all posted.

**Comment by chemphys** [comment]
I put here a comparison of DLPOLY and OpenMM. The simulation is a gas phase simulation of a cluster with 256 water molecules, for 100 steps. @zonca , I put here the pdb file I used. Would you mind running a 100 step simulation for that system (is a gas phase system) and put here ( [water256.pdb.zip](https://github.com/paesanilab/clusters_ultimate/files/1801181/water256.pdb.zip) ) the time it takes with 1, 2, 4 and 8 cores in ockham? I will update the figure below when you have it.

Thanks!

![timing_platforms_20180311](https://user-images.githubusercontent.com/10054173/37262163-a16647ac-255e-11e8-95c3-9e37b1fb69ce.jpg)

**Comment by zonca** [comment]
@chemphys I compiled the `mbpol_openmm_plugin` with the CPU platform on ockam under your account.
I think it is quicker if you run the benchmark with the same code you used for MBnrg, just replace `mbnrg.xml` with `mbpol.xml`, and you can test both the Reference Platform and the CPU platform.

**Comment by chemphys** [comment]
Thanks @zonca ! I will do it.
I would also like to have a chat tomorrow again. We want now to implement the PBC, and we (@dgasmith , @fpaesani , @agoetz and myself) think that it will be better to try to use the actual openMM electrostatics, or the one that you have implemented. We don't know exactly how can we tackel this, but I hope I can have a draft of the idea tomorrow together with you. Since you already have a full electrostatics set up, I might just need to add a few functions in my classes to get what your code needs. Let's see the speed, and tomorrow we talk, if that works for you. Thanks a lot for your help!

**Comment by zonca** [comment]
Ok for a call tomorrow

**Comment by chemphys** [comment]
Hi @fpaesani , @zonca , @agoetz , and @dgasmith . Find here updated the figure with the corresponding timings for OpenMM - MBpol. Seeing this, I think it will be great if we can use the real part of the electrostatics from the clusters code, and then get the necessary information to run the Ewald part from Andrea's code. I will work on this during the next days.

![timing_platforms_20180311](https://user-images.githubusercontent.com/10054173/37490739-bbdd53c6-2858-11e8-913b-af5482ca887a.jpg)

**Comment by chemphys** [comment]
Hey @fpaesani , @dgasmith , and @agoetz 

The table below shows the time (in seconds) it takes as a function of number of cores to perform *100 steps* for a system of *256 water molecules*. I updated the times for the total simulation (all contributions) for MB-nrg and MB-pol because the machine I am using is a new one and is faster than my old one. The times now have dropped dramatically.

 | Number of cores | 1B | 2B | 3B | Electrostatics | Simulation (openMM MB-pol plugin) | Simulation (openMM MB-nrg plugin) | 
 | --- | --- | --- | --- | --- | --- | --- |
 | 1 |    1.0971 |   12.6930 |   10.4166 |  581.4392 |  607.1876 | 178.9995  |
 | 2 |    1.0360 |   10.0036 |    9.9666 |  369.2526 |  376.4119 | 92.1559  |
 | 4 |    1.0391 |    6.9663 |   10.2369 |  268.8121 |  275.7520 | 48.7123  |
 | 8 |    1.1982 |    6.8685 |    9.7938 |  213.2718 |  234.2626 |  27.4574 |

From here we can see a few things:
1. The electrostatics for MB-nrg plugin scales practically perfectly with the number of cores
2. The energy for MB-nrg plugin is way faster than the energy for MB-pol plugin
3. The electrostatics takes a huge percentage of the total calculation time.

From here, I think that we should use the direct part of the Clusters_Ultimate electrostatics, and try to hook it to the ewald part of @zonca , What do you think?

**Comment by fpaesani** [comment]
@chemphys @dgasmith @zonca @agoetz This is quite promising! Let's see what happens in periodic boundary conditions, keeping in mind that this still uses the iterative method to converge the induced dipoles, which implies that there will be additional speedup when we move to DIIS or ASPC. Thanks!

**Comment by zonca** [comment]
@chemphys, great performance numbers!
I agree with your plan

**Comment by agoetz** [comment]
@chemphys This looks great and as @fpaesani  says, we should see significant speedup during MD with DIIS or ASPC. Are the PIP numbers (1B/2B/3B) from the MB-pol or MB-nrg plugin? Do you know why these terms parallelize so badly (or not at all)?

**Comment by chemphys** [comment]
This is from OpenMM-MB-pol. I don't know why the scaling is so bad for them. Maybe @zonca knows.

**Comment by dgasmith** [comment]
Previous tests showed reasonable scaling for the n-body terms in MB-nrg. It seems like something specific to these runs.

**Comment by zonca** [comment]
Its because they are single-threaded. Only Electrostatics supports multiple
threads.

Il lun 2 apr 2018, 22:33 Daniel Smith <notifications@github.com> ha scritto:

**Comment by agoetz** [comment]
OK, good. @chemphys do you have timings for the threaded 1B/2B/3B terms in the implementation that you developed with @dgasmith ? Do you know how many iterations the electrostatics require to converge at each time step? This will give us an idea of the maximum speedup that we can expect due to DIIS or ASPC.

**Comment by chemphys** [comment]
OpenMM will be removed from MBX. Closing.
