### ISSUE TITLE
correlation.dat 2nd column incorrect for fit-2b-ttm

### ISSUE THREAD

**Issue by ctangtar** [paesanilab/MBX#66]
for fit-2b-ttm, the predicted energy from the ttm model(2nd column of correlation.dat) is printed incorrectly. when printing to corrleation.dat, the dispersion is uses the wrong parameters, change final_l to final_nl.

**Comment by agoetz** [comment]
Thank you for catching and reporting. I opened a bugfix PR in potential_fitting with @chemphys to review. Closing this issue here as it is fixed in potential_fitting. Thanks!
