### ISSUE TITLE
Library in the makefile of the i-pi plugin isn't linked correctly

### ISSUE THREAD

**Issue by louil95** [paesanilab/MBX#77]
Hello,

on my computer (Debian) the Makefile of the i-pi plugin isn't linked correctly.
Here is my proposed fix, which worked on my machine:

Replace:
LIBS = -lmbxlib -fopenmp -lfftw3
LIBDIR = -L$(MBX_HOME)/install/lib/static

With:
LIBS = -l:libmbx.a -fopenmp -lfftw3
LIBDIR = -L$(MBX_HOME)/install/lib

Greetings Louis

**Comment by chemphys** [comment]
Hello @louil95 !

Thanks for the headsup. I will have this fixed today. As you may have seen, we just changed the whole installation process and I completely missed the i-pi makefile.

**Comment by chemphys** [comment]
Hello! The changes have been applied to the master branch. Thanks for letting us know!
I will close the issue now.
