### ISSUE TITLE
Meaning of  max_n_eval_Xb not clear

### ISSUE THREAD

**Issue by louil95** [paesanilab/MBX#79]
Hello,

Thanks for the nice program!

it is not mentioned in the README, but the mbx.json file includes three variables:

"max_n_eval_1b"    : 500,
"max_n_eval_2b"    : 500,
"max_n_eval_3b"    : 500,

From the file system.cpp its seems like those parameter are defining the range of calculated X-body interactions.
Does this mean, after max_n_eval_Xb > 500 the other interactions are simply neglected?
Or is it just something about the distribution of workload on the threads?

The first one would have horrendous consequences for the user.
You might want to add the description in the README.

Greetings 

Louis

**Comment by chemphys** [comment]
Hello Lois! It is not in the README. I may remove them from the code, actually. The initial idea of that was to control the amount of monomers, dimers and trimers sent at once to the polynomials. Effectively, now is done 1 by 1, so there is not much use for those variables. 

You can just ignore them. Tha maximum number referes just to that, the maximum n-mers passed at once to the polynomials. Nothing is ignored. This means that, if tehre are 1000 mons and max_n_eval is set to 500, there will be 2 calls to the polynomials, first one with 500 and second one with 500. 

If you don't mind, I would really appreciate to post these type of questions to the MBX users google group, so other people that may wonder the same thing can actually have the answer directly. I will copy this post there, keeping the issue open to remember to change this so it does not confuse anybody else!

Thanks for the heads-up!

Marc

**Comment by louil95** [comment]
Thanks for the answer. I’m sorry I overread the keeping the issue open part.

**Comment by chemphys** [comment]
No problem!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
