### ISSUE TITLE
OpenMM plugin support

### ISSUE THREAD

**Issue by smlee99** [paesanilab/MBX#80]
Hi MB-pol devs. This is not directly related to the current version of MBX but I'd like to ask some questions regarding openMM support. I remembered that MBX previously supported the openMM plugin and I once installed the plugin version mbpol-1.0-py3.5-linux-x86_64.egg. It seems like such plugin is now completely removed from MBX (as seen in #40). Can I ask the reason why openMM is no longer supported by MBX? And would it be still okay to utilize the previously installed MBX openMM plugin?

**Comment by chemphys** [comment]
Hello,

We decided to discontinue support to OpenMM for a variety of reason, one of them being the speed of the energy calculation. We strongly recommend to migrate to LAMMPS. It may take 1 or 2 days to get familiar with it, but you will see a 10x-15x speedup and the possibility to use both OpenMP and MPI parallelization. There are some examples of lammps inputs for an MBX simulations in plugins/lammps/examples , and the installation procedure is detailed in the README of MBX. For LAMMPS questions, please read the LAMMPS manual for general information, but if you have other questions about MBX+LAMMPS, please use our google groups (see link in README), and we will be happy to help. 

Have a good day!

**Comment by chemphys** [comment]
Closing this issue.
