### ISSUE TITLE
Stress Tensor

### ISSUE THREAD

**Issue by tgmaxson** [paesanilab/MBX#86]
How is the stress tensor implemented for MBX within LAMMPS when using periodic boundary conditions?  Is the contribution to the stress tensor purely from the motion of the particles or is there some contribution from MBX directly?

**Comment by chemphys** [comment]
Hello,
Please do not use the issues to ask questions. We have our google groups for that.

Having said that, to answer your question, you can run NPT simulations with lammps + mbx. The contribution to the stress tensor coming from the MBX energy contributions are accounted for, and given to lammps. 

If there is a follow up question, please use the google groups and we will happily help you!
