### ISSUE TITLE
Help! Fortran interface does not work!

### ISSUE THREAD

**Issue by korolrom** [paesanilab/MBX#95]
Hi MBX developers, I am trying to use your code to run a Fortran calculation. During the compilation of `MBX/examples/PEFs/src/fortran/example_pbc.f90`, the compiler complains that the function `bblock::System::SetNewParamsElec(bool)` is undefined. Indeed, I see that this function definition is removed in master branch. 
https://github.com/paesanilab/MBX/blob/d7390aa807849ad7b1b73cfb85b3107f0bfad2d5/src/bblock/system.cpp#L179

Since the C++ external example `MBX/examples/PEFs/src/C++/example_pbc.cpp` compiles no problem and produces required output, I assume this is due to a change (or many changes) in the code for which the Fortran interface was not adjusted. 

My question is: do you have a working Fortran interface for MBX 1.0 or any other usable version of MBX? If not, can you help me figure out the best way to make it happen? I just need to have accurate potential energy of water, no other molecules, no gradients. I asked on the [forum](https://groups.google.com/g/mbx-users/c/d4SFlzv8OLY/m/lRPcGp0VAAAJ), but I haven't heard back yet.

Thanks for any help!

**Comment by korolrom** [comment]
Update: I added back the definition of  `bblock::System::SetNewParamsElec(bool)` in  [MBX/src/bblock/system.cpp](https://github.com/paesanilab/MBX/blob/d7390aa807849ad7b1b73cfb85b3107f0bfad2d5/src/bblock/system.cpp#L179) by uncommenting it and the example as well as example_pbc seem to work now producing results that look identical to the C++ output example up to the output precision. 

Can anyone please confirm that this is a suitable workaround?
I can imagine this function must have been reimplemented in some other way, so adding it back might cause side-effects.

**Comment by Miniland1333** [comment]
@korolrom this issue has been fixed in the recent release of MBX v1.1. This updated version should work for your use case with Fortran.

Closed by #96
